name: WebdriverIO Tests CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  wdio-test:
    name: "WebdriverIO Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Allure commandline via NPM
        run: npm install -g allure-commandline --save-dev

      - name: Run WebdriverIO tests
        run: npx wdio run wdio.conf.js
        continue-on-error: true

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-history

      - name: Build Allure report
        run: allure generate allure-results --clean
        if: always()

      - name: Check allure-results directory
        run: ls -la allure-results
        if: always()

      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
